[build]
  command = "npm run build:client && cd netlify/functions && npm install"
  functions = "netlify/functions"
  publish = "dist/spa"

[functions]
  # Don't bundle these modules, use them from node_modules
  external_node_modules = ["express", "cors", "serverless-http", "dotenv"]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
