[build]
  command = "npm run build:client && cd netlify/functions && npm install"
  functions = "netlify/functions"
  publish = "dist/spa"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "22.21.0"
  # Force npm usage instead of pnpm
  NETLIFY_USE_NPM = "true"

[functions]
  # Don't bundle these modules, use them from node_modules
  external_node_modules = ["express", "cors", "serverless-http", "dotenv"]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

# SPA routing - redirect all non-API requests to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# HTTP to HTTPS redirect (required for Web Speech API)
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Security headers for Web Speech API and microphone access
[[headers]]
  for = "/*"
  [headers.values]
    # Required for Web Speech API and microphone access
    Permissions-Policy = "microphone=*, geolocation=*, camera=*"
    # Allow HTTPS and localhost for speech recognition
    Content-Security-Policy = "upgrade-insecure-requests"
    # Ensure secure context for speech APIs
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
